[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "maturin_template"
dynamic = ["version"]
description = "A Rust CLI bundled as a Python package"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
requires-python = ">=3.8"
readme = "README.md"
license = { text = "MIT" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Rust",
    "Programming Language :: Python :: 3",
]

[tool.maturin]
bindings = "bin"
# manifest-path = "Cargo.toml"
module-name = "maturin_template"